title:               Charlene Adhiambo
url:                 https://charlenewebsite.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Charlene Adhiambo
  url:               https://charlenewebsite.github.io
  email:             alaro18@yahoo.com
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist